services:
  # Backend Flask App
  - type: web
    name: sahaayak-backend
    runtime: python3
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend React App (Static Site)
  - type: web
    name: sahaayak-frontend  
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
